name: c4tv_player
description: "C4TV Player"
publish_to: "none"

version: 0.7.0+23

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  get_it: ^7.2.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  video_player: ^2.9.2

  provider: ^6.1.1
  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.34
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0
  flutter_in_app_pip: ^1.7.4
  flutter_launcher_icons: ^0.14.4
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  drift_dev: any
  sqlite3: any
  path_provider: any
  path: any
  meta: any
  file_picker: ^8.0.0+1
  uuid: ^4.5.1
  collection: ^1.19.1
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.2
  package_info_plus: ^8.0.0
  wakelock_plus: ^1.2.5
  crypto: ^3.0.6
  window_manager: ^0.4.3
  focusable_control_builder: ^1.0.0

dev_dependencies:
  msix: ^3.16.8
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  build_web_compilers: ^4.1.5

  build: any
  mockito: ^5.4.6

msix_config:
  output_name: "C4TVPlayer"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  image_path: "assets/logo.png"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  linux:
    generate: true
    image_path: "assets/logo.png"

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
